### ISSUE TITLE
Titlebar is always dimmed on Qt5 Wayland

### ISSUE THREAD

**Issue by Eloston** [FedoraQt/QGnomePlatform#125]
Not sure if this is a known issue, but here we are.

Because of 6a3e8ffa83fff2cd33cb1ce1726566587d43311f, Qt5 applications running on Wayland will always have their titlebar in an inactive/unfocused state. Reverting this commit seems to restore the correct behavior.

Environment:

* Debian 11 (Qt 5.15.2)
* adwaita-qt 1.4.2

**Comment by grulja** [comment]
cc: @polter-rnd

**Comment by polter-rnd** [comment]
Looks like it's because https://github.com/FedoraQt/QGnomePlatform/commit/6a3e8ffa83fff2cd33cb1ce1726566587d43311f was aimed on Fedora-patched Qt and works incorrectly on vanilla 5.15.2 (which did not have that problem with titlebar dimming originally), sorry. I will look in detail later, will try to fix for both
