### ISSUE TITLE
Set QT_SCREEN_SCALE_FACTORS=2 for HiDPI

### ISSUE THREAD

**Issue by benwaffle** [FedoraQt/QGnomePlatform#25]
With `QT_SCREEN_SCALE_FACTORS=2` and `QT_AUTO_SCREEN_SCALE_FACTOR` unset, HiDPI works perfectly for me in Qt

![screenshot from 2017-07-30 15-40-50](https://user-images.githubusercontent.com/1713819/28754469-998a6e9a-753d-11e7-867b-159929a9b08b.png)

**Comment by garrett** [comment]
Wow! Setting the scale factors env variable in my /etc/profile.d/ directory fixes Qt apps on my HiDPI laptop. I just thought Qt apps didn't properly support HiDPI this whole time.

It would be great to have this fixed by default.

Note: I haven't tried to see what happens with an external monitor yet. Or what happens if the flag is turned on for a non-HiDPI computer.

**Comment by garrett** [comment]
Aha, everything is tiny on a normal DPI monitor. Ah well then.

**Comment by grulja** [comment]
I don't think this should be set in any platform theme. It should be either configured by the user or Qt should do this automatically. On Wayland this is not needed at all.
