### ISSUE TITLE
Upstream?

### ISSUE THREAD

**Issue by probonopd** [FedoraQt/QGnomePlatform#46]
Do you intend to upstream this to Qt so that it will eventually become of Qt by default?

**Comment by grulja** [comment]
I was thinking about it, but right now it's easier for me to do the development here. Maybe we can upstream it for Qt 6.

**Comment by KAMiKAZOW** [comment]
I didn't through the merged pull requests but if those contain non-trivial changes, you would need to get their permission for upstreaming because Qt Company needs a license to allow selling proprietary versions.

If upstreaming is a serious consideration, maybe relicense to MIT or 2-clause BSD sooner rather than later.

**Comment by gnidorah** [comment]
They already have the following plugin
https://code.qt.io/cgit/qt/qtbase.git/tree/src/plugins/platformthemes/gtk3
You could test it with `export QT_QPA_PLATFORMTHEME="gtk3"`
Though in contrast to `qgnomeplatform` its unable to read settings from dconf database

**Comment by probonopd** [comment]
@gnidorah 
Scope of Gnome > Scope of Gtk

**Comment by probonopd** [comment]
So this means that you do __not__ intend to upstream this to Qt?

**Comment by KAMiKAZOW** [comment]
Considering that nobody relicensed their contributions here and in addition to that TQtC's hostile moves regarding FOSS LTS versions, I don't think there is any will to upstream this.

**Comment by grulja** [comment]
For me the main reason is that I would loose flexibility to make a release whenever I want, or depend on whatever I want (e.g. Adwaita-qt).
